name    'puppetlabs-vswitch'
version '0.2.0'
source  'https://github.com/stackforge/puppet-vswitch'
author  'Endre Karlson, Dan Bode, Ian Wells, Gilles Dubreuil'
license 'Apache License 2.0'
summary 'Puppet module for OpenVSwitch and other vSwitches'
description 'Puppet module to install and configure the OpenVSwitch and other vSwitches'
project_page 'https://github.com/stackforge/puppet-vswitch'
