name    'puppet-vswitch'
version '0.0.1'
source  'https://github.com/ekarlso/puppet-vswitch'
author  'Endre Karlson'
license 'Apache License 2.0'
summary 'Puppet module for OpenVSwitch and other vSwitch's'
description 'Puppet module to install and configure the OpenVSwitch and other vSwitch's'
project_page 'https://github.com/ekarlso/puppet-vswitch'
